### ISSUE TITLE
Project to-do list

### ISSUE THREAD

**Issue by rliess** [rliess/course-catalog-rest-api#1]
# Issues - to do list

### Methods to create

  - [x] exec
  - [x] getAuthenticatedUser
  - [x] createUser
  - [x] getCourses (single and all)
  - [x] createCourse
  - [x] updateCourse
  - [x] deleteCourse

### Header

- [x] Display top bar displaying Sign-In/Sign-Out buttons (depending on state)

### Courses

- [x] Retrieve list of courses and display them
- [x] Link to _Course Detail_ screen
- [x] Render link to the _Create Course_ screen

### Course Detail

- [x] Retrieve the course's details from the API
- [x] Render the course _description_ and _materials needed_ in markdown
- [x] Display course detail
- [x] Render link to _Delete Course_ button
- [x] Render link to _Update Course_ button
- [x] _Update Course_ and _Delete Course_ buttons should only be displayed if here's an authenticated user and the authenticated user's ID matches that of the user who owns the course.
- [x] If the requested course isn't found redirect to the /notfound route

### Create Course

- [x] Enables users to input and save a new course

### Update Course

- [x] Enables users to update a course's content
- [x] Redirect users to the /forbidden route if the requested course isn't owned by the authenticated user.

### Sign In

- [x] Enables registered users to sign in

### Sign Up

- [x] Enables a new user to sign up

### Sign Out

- [x] Sign's out the currently authenticated user

### Private Route

- [x] Create higher-order-component for protected routes

### NotFound

- [x] Displays a message letting the user know that the requested page can't be found.

### Forbidden

- [x] Displays a message letting the user know that they can't access the requested page.

### UnhandledError

- [x] A message should be displayed letting the user know that an unexpected error has occurred.

#### Validation Errors

- [x] The _Sign Up_, _Create Course_ and _Update Course_ components should display validation errors returned from the API

## Implement Authentication

- [x] Manage global state using the React Context API
- [x] Create SignIn method
- [x] Create SignOut method
- [x] Persist user credentials even if the browser tab is refreshed
- [x] After a user successfully signs in, the user should be redirected back to the previous route

## Setup routes with React Router

The following routes are necessary

- [x] /
- [x] /courses/create (protected)
- [x] /courses/:id/update (protected)
- [x] /courses/:id
- [x] /signin
- [x] /signup
- [x] /signout
- [x] /notfound
- [x] /forbidden
- [x] /error

## Create User-friendly Messages

- [x] If a route isn't matched the NotFound component should be rendered.
- [x] Throughout the application, users should be redirected to the /error path when requests to the REST API return a "500 Internal Server Error" HTTP status code.
